//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPProject.Data
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    public partial class Customer : Entity
    {
        public Customer()
        {
            this.JournalOperations = new HashSet<JournalOperation>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual ICollection<JournalOperation> JournalOperations { get; set; }
    }
}
