//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPProject.Data
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    public partial class ExpensesCategory : Entity
    {
        public ExpensesCategory()
        {
            this.Expenses = new HashSet<Expense>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public byte[] Description { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
    }
}
