//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPProject.Data
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    public partial class ExpencesByPeriod : Entity
    {
        public int ID { get; set; }
        public int ExpenceId { get; set; }
        public int PeriodId { get; set; }
        public decimal Ammount { get; set; }
        public string Description { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual Period Period { get; set; }
    }
}
