//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPProject.Data
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    public partial class Expense : Entity
    {
        public Expense()
        {
            this.ExpencesByPeriods = new HashSet<ExpencesByPeriod>();
        }
    
        public int ExpensesID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ICollection<ExpencesByPeriod> ExpencesByPeriods { get; set; }
        public virtual ExpensesCategory ExpensesCategory { get; set; }
    }
}
