//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPProject.Data
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    public partial class Period : Entity
    {
        public Period()
        {
            this.ExpencesByPeriods = new HashSet<ExpencesByPeriod>();
            this.JournalOperations = new HashSet<JournalOperation>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<ExpencesByPeriod> ExpencesByPeriods { get; set; }
        public virtual ICollection<JournalOperation> JournalOperations { get; set; }
    }
}
